sudo: required
services:
  - docker

before_install:
  - docker build -t sumankumar235/react-docker -f Dockerfile.dev .

script:
  - docker run sumankumar235/react-docker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "react-docker"
#   env: "ReactDocker-env"
#   bucket_name: ""
#   bucket_path: ""
#   on:
#     branch: master
